- name: "Copy main NixOS configuration to {{ hostname }}"
  ansible.builtin.template:
    src: templates/{{ item }}.nix.j2
    dest: /etc/nixos/{{ item }}.nix
    mode: '0644'
    owner: root
    group: root
  loop:
    - configuration
    - users
    - filesystems
    - hyprland

- name: "Copy Hyprland configuration"
  ansible.builtin.copy:
    src: "files/{{ item }}-{{ hostname }}-hyprland.conf"
    dest: "/home/{{ item }}/.config/hypr/hyprland.conf"
    mode: '0644'
    owner: "{{ item }}"
    group: "{{ item }}"
    state: file
  with_items: "{{ usernames }}"
