- name: "Create NixOS config dirs"
  ansible.builtin.file:
    path: "/etc/nixos/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - users
    - desktop

- name: "Copy main NixOS configuration"
  ansible.builtin.template:
    src: templates/system/{{ item }}.nix.j2
    dest: /etc/nixos/{{ item }}.nix
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - configuration
    - filesystems
    - flake

- name: "Copy user NixOS configuration"
  ansible.builtin.template:
    src: templates/users/{{ item }}.nix.j2
    dest: /etc/nixos/users/{{ item }}.nix
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - mike

- name: "Copy Gnome environment NixOS configuration"
  ansible.builtin.template:
    src: templates/desktop/gnome/{{ item }}.nix.j2
    dest: /etc/nixos/desktop/{{ item }}.nix
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - gnome
  when:
    - gnome_enabled is defined
    - gnome_enabled

- name: "Copy Hyprland NixOS configuration"
  ansible.builtin.template:
    src: templates/desktop/hypr/{{ item }}.nix.j2
    dest: /etc/nixos/desktop/{{ item }}.nix
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - hyprland
  when:
    - hyprland_enabled is defined
    - hyprland_enabled

- name: "Copy Hyprland user configuration for {{ username }}"
  ansible.builtin.copy:
    src: "files/{{ username }}-{{ hostname }}-{{ item }}.conf"
    dest: "/home/{{ username }}/.config/hypr/{{ item }}.conf"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - hyprland
    - hypridle
    - hyprlock
  when:
    - hyprland_enabled is defined
    - hyprland_enabled
