- name: "Copy main NixOS configuration"
  ansible.builtin.template:
    src: templates/{{ item }}.nix.j2
    dest: /etc/nixos/{{ item }}.nix
    mode: '0644'
    owner: root
    group: root
  loop:
    - configuration
    - filesystems

- name: "Create NixOS users dir"
  ansible.builtin.file:
    path: /etc/nixos/users
    state: directory
    mode: '0755'

- name: "Copy user NixOS configuration"
  ansible.builtin.template:
    src: templates/users/{{ item }}.nix.j2
    dest: /etc/nixos/users/{{ item }}.nix
    mode: '0644'
    owner: root
    group: root
  loop:
    - mike

- name: "Copy Gnome environment NixOS configuration"
  ansible.builtin.template:
    src: templates/{{ item }}.nix.j2
    dest: /etc/nixos/{{ item }}.nix
    mode: '0644'
    owner: root
    group: root
  loop:
    - gnome
  when:
    - gnome_enabled is defined
    - gnome_enabled == True

- name: "Copy Hyprland NixOS configuration"
  ansible.builtin.template:
    src: templates/{{ item }}.nix.j2
    dest: /etc/nixos/{{ item }}.nix
    mode: '0644'
    owner: root
    group: root
  loop:
    - hyprland
  when:
    - hyprland_enabled is defined
    - hyprland_enabled == True

- name: "Copy Hyprland user configuration for {{ username }}"
  ansible.builtin.copy:
    src: "files/{{ username }}-{{ hostname }}-{{ item }}.conf"
    dest: "/home/{{ username }}/.config/hypr/{{ item }}.conf"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - hyprland
    - hypridle
    - hyprlock
  when:
    - hyprland_enabled is defined
    - hyprland_enabled == True
