- name: "Create NixOS config dirs"
  ansible.builtin.file:
    path: "/home/mike/sync/git/nixos/nixos-configuration/{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - system
    - users
    - desktop
    - "users/{{ username }}/secrets"
    - "users/{{ username }}/software"

- name: "Copy main NixOS configuration"
  ansible.builtin.template:
    src: templates/system/{{ item.src }}.nix
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - { src: 'configuration', dest: '/home/mike/sync/git/nixos/nixos-configuration/configuration.nix' }
    - { src: 'filesystems', dest: '/home/mike/sync/git/nixos/nixos-configuration/system/filesystems.nix' }
    - { src: 'backup', dest: '/home/mike/sync/git/nixos/nixos-configuration/system/backup.nix' }
    - { src: 'flake', dest: '/home/mike/sync/git/nixos/nixos-configuration/flake.nix' }

- name: "Copy user NixOS configuration"
  ansible.builtin.template:
    src: templates/users/{{ item.src }}.nix
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - { src: "{{ username }}", dest: "/home/mike/sync/git/nixos/nixos-configuration/users/{{ username }}.nix" }
    - { src: 'flatpak', dest: "/home/mike/sync/git/nixos/nixos-configuration/users/{{ username }}/software/flatpak.nix" }
    - { src: 'home', dest: "/home/mike/sync/git/nixos/nixos-configuration/users/{{ username }}/home.nix" }

- name: "Copy user NixOS home-manager software configuration(s)"
  ansible.builtin.template:
    src: templates/users/software/{{ item }}.nix
    dest: /home/mike/sync/git/nixos/nixos-configuration/users/{{ username }}/software/{{ item }}.nix
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - atuin
    - bash
    - btop
    - ghostty
    - git
    - starship
    - zoxide

- name: "Copy Gnome environment NixOS configuration"
  ansible.builtin.template:
    src: templates/desktop/gnome/{{ item }}.nix
    dest: /home/mike/sync/git/nixos/nixos-configuration/desktop/{{ item }}.nix
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - gnome

- name: "Copy Hyprland NixOS configuration"
  ansible.builtin.template:
    src: templates/desktop/hypr/{{ item }}.nix
    dest: /home/mike/sync/git/nixos/nixos-configuration/desktop/{{ item }}.nix
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - hyprland

- name: "Copy Hyprland user configuration for {{ username }}"
  ansible.builtin.copy:
    src: "files/hypr/{{ item }}.conf"
    dest: "/home/{{ username }}/.config/hypr/{{ item }}.conf"
    mode: '0644'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - hyprland
    - hypridle
    - hyprlock
  when:
    - hyprland_enabled is defined
    - hyprland_enabled

- name: "Copy SOPS encrypted secret file"
  ansible.builtin.copy:
    src: "files/secrets/global.yaml"
    dest: "/home/mike/sync/git/nixos/nixos-configuration/users/{{ username }}/secrets/global.yaml"
    mode: '0600'
    owner: "{{ username }}"
    group: "{{ username }}"
